#Main spring configuration
spring.application.name=notification-service
server.port=0


utils.enabled-developer-messages=true
utils.time-format=dd-MM-yyyy k:m:s

#DATABASE
spring.datasource.driver-class-name=org.postgresql.Driver
#url to database
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
#login and password
spring.datasource.username=postgres
spring.datasource.password=admin

#Other database configuration
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.sql.init.mode=never
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#DEBUG
debug=false

#EUREKA
eureka.client.service-url.defaultZone=http://localhost:8761/eureka


# Kafka Properties (Consumer)
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.template.default-topic=notificationCreateTopic
spring.kafka.consumer.group-id=notificationServiceId
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.json.type.mapping=notificationCreate:me.igrade.notifications.teacherstudentdata.events.NotificationCreateEvent,notificationMark:me.igrade.notifications.users.events.NotificationMarkEvent
