#Main spring configuration
spring.application.name=iGrade-M1-Users
server.port=8081

utils.enabled-developer-messages=true
utils.time-format=dd-MM-yyyy k:m:s


#DATABASE
spring.datasource.driver-class-name=org.postgresql.Driver
#url to database
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
#login and password
spring.datasource.username=postgres
spring.datasource.password=admin

#Other database configuration
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.sql.init.mode=never
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#RSA KEYS
rsa.private-key=classpath:certs/private.pem
rsa.public-key=classpath:certs/public.pem


#DEBUG
debug=false
