#Main spring configuration
spring.application.name=user-service
server.port=8092

utils.enabled-developer-messages=true
utils.time-format=dd-MM-yyyy k:m:s


#DATABASE
spring.datasource.driver-class-name=org.postgresql.Driver
#url to database
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
#login and password
spring.datasource.username=postgres
spring.datasource.password=admin


#Other database configuration
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.sql.init.mode=never
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#RSA KEYS
rsa.private-key=classpath:certs/private.pem
rsa.public-key=classpath:certs/public.pem

#Admin of service
admin.admin-emails=admin@email.com,teacher@admin.com,polnareff@gmail.com

#EUREKA
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

#DEBUG
debug=false

#Circuit breaker
management.health.circuitbreakers.enabled=true
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

#Resilince 4j properties for TeacherStudentData-Service communication
resilience4j.circuitbreaker.instances.teacherStudentData.register-health-indicator=true
resilience4j.circuitbreaker.instances.teacherStudentData.event-consumer-buffer-size=10
resilience4j.circuitbreaker.instances.teacherStudentData.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.teacherStudentData.sliding-window-size=5
resilience4j.circuitbreaker.instances.teacherStudentData.failure-rate-threshold=30
resilience4j.circuitbreaker.instances.teacherStudentData.wait-duration-in-open-state=5s
resilience4j.circuitbreaker.instances.teacherStudentData.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.teacherStudentData.automatic-transition-from-open-to-half-open-enabled=true

#Resilience4J Timeout Properties for TeacherStudentData-Service communication
resilience4j.timelimiter.instances.teacherStudentData.timeout-duration=3s

#Resilience4J Retry Properties for TeacherStudentData-Service communication
resilience4j.retry.instances.teacherStudentData.max-attempts=3
resilience4j.retry.instances.teacherStudentData.wait-duration=2s


#Resilince 4j properties for Notification-Service communication
resilience4j.circuitbreaker.instances.notification.register-health-indicator=true
resilience4j.circuitbreaker.instances.notification.event-consumer-buffer-size=10
resilience4j.circuitbreaker.instances.notification.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.notification.sliding-window-size=5
resilience4j.circuitbreaker.instances.notification.failure-rate-threshold=30
resilience4j.circuitbreaker.instances.notification.wait-duration-in-open-state=5s
resilience4j.circuitbreaker.instances.notification.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.notification.automatic-transition-from-open-to-half-open-enabled=true

#Resilience4J Timeout Properties for Notification-Service communication
resilience4j.timelimiter.instances.notification.timeout-duration=3s

#Resilience4J Retry Properties for Notification-Service communication
resilience4j.retry.instances.notification.max-attempts=3
resilience4j.retry.instances.notification.wait-duration=5s


# KAFKA SECTION

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.template.default-topic=notificationMarkTopic
spring.kafka.consumer.group-id= notificationServiceId
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.type.mapping=notificationMark:me.igrade.events.NotificationMarkEvent
